---
components:
  - name: ActixApi
    type: service
    image: rust:latest
    port: 8080
    build:
      steps:
        - directory: /app
        - copy: [Cargo.toml, Cargo.lock]
          destination: ./
        - copy: src
          destination: ./src
        - run: cargo build --release
    runtime:
      command: /app/target/release/actix-api
routes:
  - target:
      component: ActixApi
