---
components:
  - name: ActixApi
    type: service
    image: rust:latest
    port: 8080
    build:
      steps:
        - directory: /app
        - copy: [Cargo.toml, Cargo.lock]
          destination: ./
        - copy: src
          destination: ./src
        - copy: sql
          destination: ./sql
        - run: cargo build --release
    runtime:
      resources:
        - PgDatabase
      command: /app/target/release/actix-api
      variables:
        PG__URL:
          $resources: PgDatabase.url
        PG__USER:
          $resources: PgDatabase.username
        PG__PORT:
          $resources: PgDatabase.port
        PG__HOST:
          $resources: PgDatabase.host
        PG__PASSWORD:
          $resources: PgDatabase.password
        PG__DBNAME:
          $resources: PgDatabase.database
        PG__POOL__MAX_SIZE: "16"
        SERVER_ADDR: "rust.local.noop.app"
routes:
  - target:
      component: ActixApi
resources:
  - name: PgDatabase
    type: postgresql
